version: "3"

services:
  uniticket.local:
    image: ghcr.io/universitadellacalabria/uniticket:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./examples-docker:/django-project
    networks:
      - uniticket
    command: |
        bash -c "cd /django-project/ &&
        python3 manage.py migrate &&
        python3 manage.py loaddata dumps/example_conf.json &&
        python3 manage.py runserver 0.0.0.0:8000"

networks:
  uniticket:
